# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfd23948017c87d191a708b38fb1c579f595be3d01de1b3004a14d4791d12f4228c9bcb53c0eb76a05b85b89c11705dd8dda38dea22b622058d66a78db8a7254

test:
  secret_key_base: df7467b45f6c380094fb8807761698825cb4d20b1609877aa454feb3dc7bfea279105a338e5767e7f2df47f8fed72ec89d9c6ce19a336cdbfc8c9286d1a506b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
